# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e8d14f0111db81592af61a56338d6c4ba785be74cb4c5852054bf240692c39816ea1ffb6440ec0c8472ca319a68044dfb20de3250923ba58bc63a080189364a

test:
  secret_key_base: 2d277b81ff6cd7f3b5ef138654e088cc2f6b26a075e84495596ce5113f2d59042a9e7c55586376366795d2fc3a805844995e771f8efdf3797dd3327707c306b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
